name: 'sast-semgrep'

on:
  push:
  pull_request:
    types:
      - reopened
      - ready_for_review
  workflow_dispatch:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install semgrep
      run: sudo apt install python3-pip && pip install semgrep

    - name: Run semgrep
      run: result=$(semgrep --config=auto --gitlab-sast .)

    - name: Check semgrep output
      run: |
        if [[ "$result" == *"\"vulnerabilities\": []"* ]]; then
          echo "Not found any vulnerabilities"
        else
          echo "Found vulnerabilities"
          echo $result
          exit 1
        fi
